services:
  qbittorrent:
    image: "docker.io/qbittorrentofficial/qbittorrent-nox:5.1.4-2\
       @sha256:85fe2690f418dabffc4907276b3cdffcb7880c7114157b32f932d3b97bac45af"
    dns: ${GLUETUN_NETWORK_GATEWAY_ADDRESS}
    networks:
      gluetun:
        gw_priority: 1
      caddy:
        aliases: ["${QBITTORRENT_ID}"]
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
    environment:
      - QBT_LEGAL_NOTICE=confirm
    env_file:
      - common.env
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}

networks:
  gluetun:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${GLUETUN_NETWORK}
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
