#!/bin/sh

set -eu

root="$(dirname "$(realpath "$0")")/..selfhost"

deployment_path="$1"

if [ -e "$deployment_path" ]; then
    >&2 echo "File already exists at $deployment_path"
    exit 1
fi

# - Install key top-level files
# - Install non-hidden top-level directories
# - Ignore sockets anywhere
rsync -glor \
    --include='/docker-compose.yaml' \
    --include='/route-failsafe' \
    --include='/startup' \
    --include='/.env' \
    --include='/.common.env' \
    --include='/..selfhost' \
    --exclude='/.*' \
    --include='/*/' \
    --exclude='/*' \
    --exclude='._.*' \
    "$root/" "$deployment_path"

echo 'Success'
