services:
  caddy:
    build:
      tags: [caddy:local]
    networks:
      main:
        gw_priority: 1
        ipv4_address: ${MAIN_NETWORK_CADDY_ADDRESS}
      caddy:
    volumes:
      - ./volumes/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./volumes/data:/data
      - ./volumes/config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - DYNU_API_KEY=${DYNU_API_KEY}
      # Services
      - GIT_ALIAS=${CADDY_NETWORK_GIT_ALIAS}
      - JELLYFIN_ALIAS=${CADDY_NETWORK_JELLYFIN_ALIAS}
      - LIBRESPEED_ALIAS=${CADDY_NETWORK_LIBRESPEED_ALIAS}
      - QBITTORRENT_ALIAS=${CADDY_NETWORK_QBITTORRENT_ALIAS}
      - RADICALE_ALIAS=${CADDY_NETWORK_RADICALE_ALIAS}
      - VAULTWARDEN_ALIAS=${CADDY_NETWORK_VAULTWARDEN_ALIAS}
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
    internal: true
  main:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${MAIN_NETWORK}
