services:
  git:
    build:
      args:
        ROOT: /var/www/git
    networks:
      caddy:
        aliases: ["${GIT_ID}"]
    volumes:
      - ./volumes/root:/var/www/git
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
