services:
  vaultwarden:
    image: "vaultwarden/server:1.33.2-alpine\
      @sha256:63cce7624f655f83ad5bab66ef62bc3e3327116b068704bfbbda5d0c1b3003be"
    networks:
      caddy:
        aliases: ["${CADDY_NETWORK_VAULTWARDEN_ALIAS}"]
    volumes:
      - ./volumes/data:/data
    environment:
      # TODO: what does this do in practice?
      - WEBSOCKET_ENABLED=true
    env_file:
      - local.env
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
