services:
  caddy:
    build: .
    networks:
      main:
        gw_priority: 1
        ipv4_address: ${MAIN_NETWORK_CADDY_ADDRESS}
      caddy:
    volumes:
      - ./volumes/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./volumes/data:/data
      - ./volumes/config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - DYNU_API_KEY=${DYNU_API_KEY}
      # Services
      - GIT_ID=${GIT_ID}
      - JELLYFIN_ID=${JELLYFIN_ID}
      - LIBRESPEED_ID=${LIBRESPEED_ID}
      - PROWLARR_ID=${PROWLARR_ID}
      - QBITTORRENT_ID=${QBITTORRENT_ID}
      - RADICALE_ID=${RADICALE_ID}
      - SYNCTHING_ID=${SYNCTHING_ID}
      - VAULTWARDEN_ID=${VAULTWARDEN_ID}
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
    internal: true
  main:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${MAIN_NETWORK}
