services:
  vaultwarden:
    image: "docker.io/vaultwarden/server:1.33.2-alpine\
      @sha256:63cce7624f655f83ad5bab66ef62bc3e3327116b068704bfbbda5d0c1b3003be"
    networks:
      caddy:
        aliases: ["${VAULTWARDEN_ID}"]
    volumes:
      - ./volumes/data:/data
    environment:
      # Enable more efficient multi-device sync
      - WEBSOCKET_ENABLED=true
    env_file:
      - local.env
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
