#!/bin/sh

set -eux

case "${1:-}" in
    up)
        NAT_OP="-A"
        FILTER_OP="-I"
        ;;
    down)
        NAT_OP="-D"
        FILTER_OP="-D"
        ;;
    *)
        echo "Usage: $0 {up|down}" >&2
        exit 1
        ;;
esac

get_env_var() {
    sed -n "s/^$1=//p" .env
}

MAIN_NETWORK_SUBNET=$(get_env_var 'MAIN_NETWORK_SUBNET')
MAIN_NETWORK_WIREGUARD_WAN_ADDRESS=$(get_env_var 'MAIN_NETWORK_WIREGUARD_WAN_ADDRESS')
WIREGUARD_WAN_HOST_PORT=$(get_env_var 'WIREGUARD_WAN_HOST_PORT')

WIREGUARD_INTERNAL_PORT=51820

# Workaround: Docker can't expose ports on non-default gateway networks
# Ref: https://github.com/docker/compose/issues/12616#issuecomment-2721195200
iptables -t nat "$NAT_OP" PREROUTING \
    -p udp \
    --dport "$WIREGUARD_WAN_HOST_PORT" \
    ! -s "$MAIN_NETWORK_SUBNET" \
    -j DNAT --to-destination "$MAIN_NETWORK_WIREGUARD_WAN_ADDRESS:$WIREGUARD_INTERNAL_PORT"
iptables "$FILTER_OP" FORWARD \
    -p udp \
    -d "$MAIN_NETWORK_WIREGUARD_WAN_ADDRESS" \
    --dport "$WIREGUARD_INTERNAL_PORT" \
    ! -s "$MAIN_NETWORK_SUBNET" \
    -j ACCEPT
iptables -t nat "$NAT_OP" POSTROUTING \
    -p udp \
    -d "$MAIN_NETWORK_WIREGUARD_WAN_ADDRESS" \
    --dport "$WIREGUARD_INTERNAL_PORT" \
    ! -s "$MAIN_NETWORK_SUBNET" \
    -j MASQUERADE
