services:

  wireguard-lan:
    # No official Docker image exists, using linuxserver.io community image
    image: "lscr.io/linuxserver/wireguard:v1.0.20210914-ls126\
      @sha256:a27dc2b63245fa1c20fc55edf9aebf7cf3add71000557177c9fa62dba65b5d29"
    networks:
      main:
    ports:
      - ${WIREGUARD_LAN_HOST_PORT}:51820/udp
    volumes:
      - ./volumes/server-template.conf:/config/templates/server.conf:ro
      - ./volumes/config:/config
    environment:
      - SERVERURL=${DOMAIN}
      - SERVERPORT=${WIREGUARD_LAN_HOST_PORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_NETWORK_SERVER_ADDRESS}/32,${MAIN_NETWORK_SUBNET},${HOST_NETWORK_SUBNET}
      # Disable default DNS server since we run dnsmasq instead
      # Ref: https://github.com/linuxserver/docker-wireguard/issues/62#issuecomment-2010533285
      - USE_COREDNS=false
      # root is required for network setup, so 'user:' directive won't work
      # switch to PUID/PGID env vars after init
      - PUID=${PUID}
      - PGID=${PGID}
    env_file:
      - local.env
      - common.env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: ${DOCKER_RESTART}

  wireguard-lan-dnsmasq:
    image: "strm/dnsmasq\
      @sha256:dcf4c0aeb69ea6b9bca81314449d732ecd2ea021588d8a34d4be7c2304f89a39\
    "  # unversioned, the only available version for now
    network_mode: service:wireguard-lan
    command:
      - -k
      - --interface=wg0
      - --address=/${DOMAIN}/${MAIN_NETWORK_CADDY_ADDRESS}
      - --log-queries
      - --log-facility=-  # shows up in docker logs
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}

networks:
  main:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${MAIN_NETWORK}
