services:

  wireguard-lan:
    image: "lscr.io/linuxserver/wireguard\
      @sha256:a27dc2b63245fa1c20fc55edf9aebf7cf3add71000557177c9fa62dba65b5d29\
    "  # v1.0.20210914-ls126
    container_name: wireguard-lan
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - env-files/wireguard.env
      - env-files/linuxserverio.env
    environment:
      - SERVERURL=${DOMAIN}
      - SERVERPORT=${WIREGUARD_LAN_HOST_PORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_NETWORK_SERVER_ADDRESS}/32,${MAIN_NETWORK_SUBNET},${HOST_NETWORK_SUBNET}
      # Disable default DNS server since we run dnsmasq instead
      # Ref: https://github.com/linuxserver/docker-wireguard/issues/62#issuecomment-2010533285
      - USE_COREDNS=false
    ports:
      - ${WIREGUARD_LAN_HOST_PORT}:51820/udp
    volumes:
      - ./volumes/server-template.conf:/config/templates/server.conf:ro
      - ./volumes/config:/config
    restart: on-failure

  wireguard-lan-dnsmasq:
    image: "\
      strm/dnsmasq\
      @sha256:dcf4c0aeb69ea6b9bca81314449d732ecd2ea021588d8a34d4be7c2304f89a39\
    "  # unversioned, the only available version for now
    container_name: wireguard-lan-dnsmasq
    command:
      - -k
      - --address=/${DOMAIN}/${MAIN_NETWORK_CADDY_ADDRESS}
      - --log-queries
      - --log-facility=-  # shows up in docker logs
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard-lan
    restart: on-failure

networks:
  default:
    name: ${MAIN_NETWORK}
    external: true
