services:
  gluetun-gateway:
    image: "docker.io/qmcgaw/gluetun:v3.41.0\
      @sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045"
    networks:
      main:
        gw_priority: 1
      gluetun:  # NOTE: Needs to be eth0 for iptables volume to work
        ipv4_address: ${GLUETUN_NETWORK_GATEWAY_ADDRESS}
    volumes:
      - ./volumes/iptables-post-rules.txt:/iptables/post-rules.txt:ro
      - ./volumes/config:/gluetun
    environment:
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
      # root is required for network setup, so 'user:' directive won't work
      # switch to PUID/PGID env vars after init
      - PUID=${PUID}
      - PGID=${PGID}
    env_file:
      - local.env
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1  # to act as a router
    restart: ${DOCKER_RESTART}

networks:
  main:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${MAIN_NETWORK}
  gluetun:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${GLUETUN_NETWORK}
