services:
  qbittorrent:
    image: "linuxserver/qbittorrent:5.0.3\
      @sha256:94e1c4fb34b38e9b529867aefc1185a10710ea4868dcb1c4f395780d1a4c297b"
    networks:
      gluetun:
        gw_priority: 1
      caddy:
        aliases: ["${CADDY_NETWORK_QBITTORRENT_ALIAS}"]
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
    env_file:
      - env-files/linuxserverio.env
    restart: ${DOCKER_RESTART}

networks:
  gluetun:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${GLUETUN_NETWORK}
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
