services:

  wireguard:
    image: "lscr.io/linuxserver/wireguard\
      @sha256:a27dc2b63245fa1c20fc55edf9aebf7cf3add71000557177c9fa62dba65b5d29\
    "  # v1.0.20210914-ls126
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - env-files/wireguard.env
      - env-files/linuxserverio.env
    environment:
      - SERVERURL=${DOMAIN}
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_NETWORK_SERVER_ADDRESS}/32,${MAIN_NETWORK_SUBNET},${HOST_NETWORK_SUBNET}
      # Use a custom DNS server
      - PEERDNS=${MAIN_NETWORK_DNSMASQ_ADDRESS}
      # Disable unused default DNS server
      # Ref: https://github.com/linuxserver/docker-wireguard/issues/62#issuecomment-2010533285
      - USE_COREDNS=false
    ports:
      - ${WIREGUARD_SERVERPORT}:51820/udp
    volumes:
      - ./volumes/server-template.conf:/config/templates/server.conf:ro
      - ./volumes/config:/config
    restart: on-failure

networks:
  default:
    name: ${MAIN_NETWORK}
    external: true
