#!/bin/sh
set -eu

get_env_var() {
    sed -n "s/^$1=//p" .env
}

GLUETUN_NETWORK_BRIDGE=$(get_env_var 'GLUETUN_NETWORK_BRIDGE')
MAIN_NETWORK_BRIDGE=$(get_env_var 'MAIN_NETWORK_BRIDGE')
MAIN_NETWORK_GLUETUN_ADDRESS=$(get_env_var 'MAIN_NETWORK_GLUETUN_ADDRESS')
GLUETUN_NETWORK_TABLE=100

case "${1:-}" in
    up)
        RULE_OP="add"
        IPTABLES_OP="-I"
        ;;
    down)
        RULE_OP="del"
        IPTABLES_OP="-D"
        ;;
    *)
        echo "Usage: $0 {up|down}" >&2
        exit 1
        ;;
esac

ip \
    rule "$RULE_OP" \
    iif "$GLUETUN_NETWORK_BRIDGE" \
    table "$GLUETUN_NETWORK_TABLE"
ip \
    route "$RULE_OP" \
    default via "$MAIN_NETWORK_GLUETUN_ADDRESS" \
    table "$GLUETUN_NETWORK_TABLE"

iptables \
    "$IPTABLES_OP" DOCKER-USER \
    -i "$GLUETUN_NETWORK_BRIDGE" \
    -o "$MAIN_NETWORK_BRIDGE" \
    -j ACCEPT
iptables \
    "$IPTABLES_OP" DOCKER-USER \
    -i "$MAIN_NETWORK_BRIDGE" \
    -o "$GLUETUN_NETWORK_BRIDGE" \
    -m state \
    --state RELATED,ESTABLISHED \
    -j ACCEPT
