services:
  dnsmasq:
    image: strm/dnsmasq
    container_name: dnsmasq
    command:
      - -k
      - --address=/${DOMAIN}/${MAIN_NETWORK_CADDY_ADDRESS}
      - --log-queries
      - --log-facility=-  # shows up in docker logs
    cap_add:
      - NET_ADMIN
    networks:
      main-network:
        ipv4_address: ${MAIN_NETWORK_DNSMASQ_ADDRESS}
    restart: on-failure

networks:
  main-network:
    name: ${MAIN_NETWORK}
    external: true
