#!/bin/sh
set -eu

root="$(dirname "$(realpath "$0")")/..root"

route_failsafe_service_path="/etc/systemd/system/selfhost-route-failsafe@.service"
startup_service_path="/etc/systemd/system/selfhost-docker@.service"

for path in "$route_failsafe_service_path" "$startup_service_path"; do
    if [ -e "$path" ]; then
        >&2 echo "Error: file already exists at $path"
        exit 1
    fi
done

cat > "$route_failsafe_service_path" << 'EOF'
[Unit]
Description=Network failsafe routing for selfhost at %f

[Service]
Type=oneshot
WorkingDirectory=%f
ExecStart=./route-failsafe up
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

echo "Installed at $route_failsafe_service_path"

cat > "$startup_service_path" << 'EOF'
[Unit]
Description=Start apps for selfhost at %f
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
WorkingDirectory=%f
ExecStart=./startup
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

echo "Installed at $startup_service_path"

docker_dropins_path='/etc/systemd/system/docker.service.d'
mkdir "$docker_dropins_path"
echo "Initialized Docker service drop-in units directory at $docker_dropins_path"

echo 'Reloading daemon...'
systemctl daemon-reload

echo 'Success!'
