#!/bin/sh

set -eu

root="$(dirname "$(realpath "$0")")/..root"
apps_path="$root/apps"

deployment_path="$1"

shift

if [ "$#" -eq 0 ]; then
    apps=$(find "$apps_path/"* -maxdepth 0 -type d -exec basename {} \;)
else
    apps="$*"
fi

for app in $apps; do
    source_app_path="$apps_path/$app"
    target_app_path="$deployment_path/$app"

    if [ -e "$target_app_path" ]; then
        >&2 echo "File already exists at $target_app_path"
        exit 1
    fi

    rsync -rl --exclude='._.*' "$source_app_path/" "$target_app_path"
done
