services:
  librespeed:
    image: "linuxserver/librespeed:5.4.1\
      @sha256:6eb3a38fdab18af72e6c505cb98a0a239a6e38a06066fe38b2852876c5a3e1c7"
    networks:
      caddy:
        aliases: ["${CADDY_NETWORK_LIBRESPEED_ALIAS}"]
    volumes:
      - ./volumes/config:/config
    env_file:
      - env-files/linuxserverio.env
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
