services:
  ddns-updater:
    image: "qmcgaw/ddns-updater:v2.9.0\
      @sha256:ed73f1fb7ab54a8a8fa26001eecc77cc8be56cdf3fb0ca91fee831124bcbb696"
    volumes:
      - ./volumes/data:/updater/data
    environment:
      CONFIG: |
        {
          "settings": [
            {
              "provider": "dynu",
              "domain": "${DOMAIN}",
              "username": "${DYNU_USERNAME}",
              "password": "${DYNU_PASSWORD}"
            }
          ]
        }
      SERVER_ENABLED: no
    user: ${PUID}:${PGID}
    restart: ${DOCKER_RESTART}
