#!/bin/sh

set -eu

# Ref: adr/systemd-startup.md

root="$(dirname "$(realpath "$0")")"

"$root"/configure up
# using "--all-resources create" since "up" won't work if no service is defined
docker compose --project-directory "$root" --all-resources create

for app_path in "$root"/*; do
    if ! [ -d "$app_path" ]; then
        continue
    fi

    if [ -f "$app_path/configure" ]; then
        "$app_path/configure" up
    fi

    docker compose --project-directory "$app_path" up --detach
done
