services:
  git:
    build:
      tags: [git:local]
      args:
        ROOT: /var/www/git
    networks:
      caddy:
        aliases: ["${CADDY_NETWORK_GIT_ALIAS}"]
    volumes:
      - ./volumes/root:/var/www/git
    restart: ${DOCKER_RESTART}

networks:
  caddy:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_${CADDY_NETWORK}
